controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_fallback:
    path: /{wildcard}
    controller: App\Controller\MainController::index
    requirements:
        wildcard: .*
